services:
    wyd2016bundle.alias.manager_service:
        alias:                          doctrine

    wyd2016bundle.pilgrim_application.repository:
        arguments:
            -                           Wyd2016Bundle\Entity\PilgrimApplication
        class:                          Wyd2016Bundle\Entity\Repository\PilgrimApplicationRepository
        factory:                        [@wyd2016bundle.alias.manager_service, getRepository]

    wyd2016bundle.scout_application.repository:
        arguments:
            -                           Wyd2016Bundle\Entity\ScoutApplication
        class:                          Wyd2016Bundle\Entity\Repository\ScoutApplicationRepository
        factory:                        [@wyd2016bundle.alias.manager_service, getRepository]
