#!/bin/bash

<<COMMENT

app/console assetic:dump --env=prod

app/console assets:install public_html

app/console doctrine:migrations:diff
app/console doctrine:migrations:migrate
app/console doctrine:migrations:status
app/console doctrine:schema:update --force
app/console doctrine:fixtures:load -vvv

app/console fos:user:create user email password --super-admin
app/console fos:user:promote user ROLE_ADMIN
app/console fos:user:change-password user newpassword

app/console translation:extract --config=routes --keep pl en
app/console translation:update --output-format=yml --dump-messages en SelectedBundle

COMMENT

app/console $@
