registration_scout_confirm:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:scoutConfirm
    methods:                            [GET]
    path:                               /scout/{hash}
    requirements:
        hash:                           "[0-9a-f]{32}$"
