registration_success:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:success
    methods:                            [GET]
    path:                               /success
