registration_volunteer_confirm:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:volunteerConfirm
    methods:                            [GET]
    path:                               /volunteer/{hash}
    requirements:
        hash:                           "[0-9a-f]{32}$"
