framework:
    csrf_protection:                    true
    default_locale:                     %locale%
#    esi:                                ~
    form:                               ~
    fragments:                          ~
    http_method_override:               true
    router:
        resource:                       "%kernel.root_dir%/config/routing.yml"
        strict_requirements:            ~
    secret:                             %secret%
#    serializer:
#        enable_annotations:             true
    session:
#        handler_id set to null will use default session handler from php.ini
        handler_id:                     ~
    templating:
        assets_version:                 %assets_version%
        assets_version_format:          static/%%2$s/%%1$s
        engines:
            -                           twig
    translator:
        fallback:                       %locale%
    trusted_hosts:                      ~
    trusted_proxies:                    ~
    validation:
        enable_annotations:             false
        enabled:                        true
