twig:
    debug:                              "%kernel.debug%"
    globals:
        locales:                        "%locales%"
        main_page_rules_url:            "%wyd2016.main_page_url%%wyd2016.main_page_rules_path%"
        main_page_url:                  "%wyd2016.main_page_url%"
        wyd_page_url:                   "%wyd2016.wyd_page_url%"
    strict_variables:                   "%kernel.debug%"

services:
    twig.extension.intl:
        class:                          Twig_Extensions_Extension_Intl
        tags:
            - name:                     twig.extension

    twig.extension.text:
        class:                          Twig_Extensions_Extension_Text
        tags:
            - name:                     twig.extension
