twig:
    debug:                              "%kernel.debug%"
    globals:
        age_limit:                      "%wyd2016.age.limit%"
        defaultLocale:                  "%locale%"
        locales:                        "%locales%"
        main_page:                      "%wyd2016.main_page%"
        min_age_adult:                  "%wyd2016.age.min_adult%"
        wyd_page:                       "%wyd2016.wyd_page%"
    strict_variables:                   "%kernel.debug%"

services:
    twig.extension.intl:
        class:                          Twig_Extensions_Extension_Intl
        tags:
            - name:                     twig.extension

    twig.extension.text:
        class:                          Twig_Extensions_Extension_Text
        tags:
            - name:                     twig.extension
