api_index:
    defaults:
        _controller:                    Wyd2016Bundle:Api:volunteer
    methods:                            [POST]
    path:                               /api/v1/volunteer/{id}
    requirements:
        id:                             \d+
