admin_troop_edit:
    defaults:
        _controller:                    Wyd2016Bundle:Admin/Troop:edit
    methods:                            [GET|POST]
    path:                               /admin/troop/{id}/edit
    requirements:
        id:                             \d+
