admin_troop_show:
    defaults:
        _controller:                    Wyd2016Bundle:Admin/Troop:show
    methods:                            [GET]
    path:                               /admin/troop/{id}
    requirements:
        id:                             \d+
