imports:
    - resource:                         parameters.yml
    - resource:                         security.yml

    - resource:                         bundles/assetic.yml
    - resource:                         bundles/doctrine.yml
    - resource:                         bundles/doctrine_migrations.yml
    - resource:                         bundles/framework.yml
    - resource:                         bundles/jms_i18n_routing.yml
    - resource:                         bundles/jms_translation.yml
    - resource:                         bundles/swiftmailer.yml

    - resource:                         @Wyd2016Bundle/Resources/config/repositories.yml

parameters:
    assets_version:                     15091301
    locale:                             en
    locales:
        -                               en
        -                               pl
