imports:
    - resource:                         parameters.yml
    - resource:                         security.yml

    - resource:                         bundles/assetic.yml
    - resource:                         bundles/doctrine.yml
    - resource:                         bundles/doctrine_migrations.yml
    - resource:                         bundles/fos_user.yml
    - resource:                         bundles/framework.yml
    - resource:                         bundles/jms_i18n_routing.yml
    - resource:                         bundles/jms_translation.yml
    - resource:                         bundles/swiftmailer.yml
    - resource:                         bundles/twig.yml

    - resource:                         @Wyd2016Bundle/Resources/config/repositories.yml
    - resource:                         @Wyd2016Bundle/Resources/config/services.yml

parameters:
    assets_version:                     15091301
    locale:                             en
    locales:
        -                               en
        -                               pl
    locales_pattern:                    (en|pl)
    requires_channel:                   http

    wyd2016.age.limit:                  "2016-07-01"
    wyd2016.age.max:                    120
    wyd2016.age.min_adult:              18
    wyd2016.age.min_member:             16
    wyd2016.age.min_pilgrim:            15
    wyd2016.main_page_url:              http://sdm.zhp.pl
    wyd2016.main_page_rules_path:       /regulamin
    wyd2016.troop_size:                 6
    wyd2016.wyd_page_url:               http://www.krakow2016.com
