imports:
    - resource:                         parameters.yml
    - resource:                         security.yml

    - resource:                         bundles/assetic.yml
    - resource:                         bundles/doctrine.yml
    - resource:                         bundles/doctrine_migrations.yml
    - resource:                         bundles/fos_user.yml
    - resource:                         bundles/framework.yml
    - resource:                         bundles/jms_i18n_routing.yml
    - resource:                         bundles/jms_translation.yml
    - resource:                         bundles/swiftmailer.yml
    - resource:                         bundles/twig.yml

    - resource:                         @Wyd2016Bundle/Resources/config/repositories.yml
    - resource:                         @Wyd2016Bundle/Resources/config/services.yml

parameters:
    assets_version:                     16060301
    locale:                             en
    locales:
        -                               en
        -                               es
        -                               pl
    locales_pattern:                    (en|es|pl)
    requires_channel:                   http

    wyd2016.admin.pack_size:            20
    wyd2016.age.limit:                  "2016-07-25"
    wyd2016.age.max:                    120
    wyd2016.age.min_adult:              18
    wyd2016.age.min_group_member:       14
    wyd2016.age.min_troop_member:       15
    wyd2016.email_alias:
        volunteer:                      wolontariusz{id}@sdm.krakowska.zhp.pl
    wyd2016.number.short_term_limit:    1050
    wyd2016.number.total_limit:         1050
    wyd2016.time.limit:                 "2016-06-07 22:00:00"
    wyd2016.main_page:
        rules_pilgrim:
            en:                         /terms-and-conditions-for-pilgrims
            es:                         /reglas-de-peregrinos
            pl:                         /regulamin-pielgrzyma
        rules_volunteer:
            en:                         /terms-and-conditions
            es:                         /reglas-de-voluntarios
            pl:                         /regulamin
        url:
            en:                         http://en.sdm.zhp.pl
            es:                         http://es.sdm.zhp.pl
            pl:                         http://sdm.zhp.pl
    wyd2016.size.max_group:             15
    wyd2016.size.max_troop:             6
    wyd2016.size.min_group:             2
    wyd2016.size.min_troop:             2
    wyd2016.wyd_page:
        url:
            en:                         http://www.krakow2016.com/en
            es:                         http://www.krakow2016.com/es
            pl:                         http://www.krakow2016.com
