_fos_user_security:
    prefix:                             /admin
    resource:                           "@FOSUserBundle/Resources/config/routing/security.xml"

_admin_group_show:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Group/show.yml"

_admin_group_index:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Group/index.yml"

_admin_pilgrim_show:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Pilgrim/show.yml"

_admin_pilgrim_list:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Pilgrim/list.yml"

_admin_pilgrim_index:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Pilgrim/index.yml"

_admin_troop_show:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Troop/show.yml"

_admin_troop_index:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Troop/index.yml"

_admin_volunteer_show:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Volunteer/show.yml"

_admin_volunteer_list:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Volunteer/list.yml"

_admin_volunteer_index:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/Volunteer/index.yml"

_admin_index:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/index.yml"

_admin_main:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Admin/main.yml"
    options:
        i18n:                           false

_registration_group_confirm:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/group/confirm.yml"

_registration_group_form:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/group/form.yml"

_registration_pilgrim_confirm:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/pilgrim/confirm.yml"

_registration_pilgrim_form:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/pilgrim/form.yml"

_registration_troop_confirm:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/troop/confirm.yml"

_registration_troop_form:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/troop/form.yml"

_registration_volunteer_confirm:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/volunteer/confirm.yml"

_registration_volunteer_form:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/volunteer/form.yml"

_registration_success:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/success.yml"

_registration_index:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/index.yml"

_core_homepage:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Core/homepage.yml"
    options:
        i18n:                           false
