_registration_pilgrim_confirm:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/pilgrim_confirm.yml"

_registration_volunteer_confirm:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/volunteer_confirm.yml"

_registration_pilgrim_form:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/pilgrim_form.yml"

_registration_volunteer_form:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/volunteer_form.yml"

_registration_rules:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/rules.yml"

_registration_success:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/success.yml"

_registration_index:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Registration/index.yml"

_core_homepage:
    resource:                           "@Wyd2016Bundle/Resources/config/routing/Core/homepage.yml"
    options:
        i18n:                           false
