registration_pilgrim_confirm:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:pilgrimConfirm
    methods:                            [GET]
    path:                               /{_locale}/pilgrim/{hash}
    requirements:
        _locale:                        %accepted_locales%
        hash:                           "[0-9a-f]{32}$"

registration_scout_confirm:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:scoutConfirm
    methods:                            [GET]
    path:                               /{_locale}/scout/{hash}
    requirements:
        _locale:                        %accepted_locales%
        hash:                           "[0-9a-f]{32}$"

registration_pilgrims:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:pilgrims
    methods:                            [GET|POST]
    path:                               /{_locale}/pilgrims
    requirements:
        _locale:                        %accepted_locales%

registration_scouts:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:scouts
    methods:                            [GET|POST]
    path:                               /{_locale}/scouts
    requirements:
        _locale:                        %accepted_locales%

registration_success:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:success
    methods:                            [GET]
    path:                               /{_locale}/success
    requirements:
        _locale:                        %accepted_locales%

registration_index:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:index
    methods:                            [GET]
    path:                               /{_locale}
    requirements:
        _locale:                        %accepted_locales%

core_homepage:
    defaults:
        _controller:                    Wyd2016Bundle:Core:homepage
    methods:                            [GET]
    path:                               /
