core_homepage:
    defaults:
        _controller:                    AppBundle:Core:homepage
    methods:                            [GET]
    path:                               /

registration_pilgrims:
    defaults:
        _controller:                    AppBundle:Registration:pilgrims
    methods:                            [GET|POST]
    path:                               /{_locale}/pilgrims
    requirements:
        _locale:                        %accepted_locales%

registration_scouts:
    defaults:
        _controller:                    AppBundle:Registration:scouts
    methods:                            [GET|POST]
    path:                               /{_locale}/scouts
    requirements:
        _locale:                        %accepted_locales%

registration_success:
    defaults:
        _controller:                    AppBundle:Registration:success
    methods:                            [GET]
    path:                               /{_locale}/success
    requirements:
        _locale:                        %accepted_locales%

registration_index:
    defaults:
        _controller:                    AppBundle:Registration:index
    methods:                            [GET]
    path:                               /{_locale}
    requirements:
        _locale:                        %accepted_locales%
