registration_troop_confirm:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:troopConfirm
    methods:                            [GET]
    path:                               /troop/{hash}/confirm
    requirements:
        hash:                           "[0-9a-f]{32}$"
