registration_troop_form:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:troopForm
    methods:                            [GET|POST]
    path:                               /troop
