Wyd2016Bundle\Entity\PilgrimApplication:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstName:
            - Length:
                min:                    2
                max:                    50
        lastName:
            - Length:
                min:                    2
                max:                    50
        address:
            - Length:
                min:                    10
                max:                    255
        phone:
            - Length:
                min:                    8
                max:                    15
            - Regex:
                pattern:                "/^[0-9 \+\-\(\)]{8,15}$/"
        email:
            - Email:                    ~
            - Length:
                min:                    3
                max:                    40
        dateFrom:
            - Date:                     ~
        dateTo:
            - Date:                     ~
