Wyd2016Bundle\Entity\Troop:
    properties:
        name:
            - Length:
                min:                    2
                max:                    50
        members:
            - Wyd2016Bundle\Validator\Constraints\UniqueEntities:
                field:                  pesel
                ignoreNull:             true
            - Wyd2016Bundle\Validator\Constraints\UniqueEntities:
                field:                  email
        comments:
            - Length:
                max:                    255
