Wyd2016Bundle\Entity\Volunteer:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:                     pesel
            ignoreNull:                 true
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstName:
            - Length:
                groups:
                    -                   troopMember
                min:                    2
                max:                    50
        lastName:
            - Length:
                groups:
                    -                   troopMember
                min:                    2
                max:                    50
        address:
            - Length:
                groups:
                    -                   troopMember
                min:                    10
                max:                    255
        phone:
            - Length:
                groups:
                    -                   troopMember
                min:                    8
                max:                    15
            - Regex:
                groups:
                    -                   troopMember
                pattern:                "/^[0-9 \+\-\(\)]{8,15}$/"
        email:
            - Email:
                groups:
                    -                   troopMember
            - Length:
                groups:
                    -                   troopMember
                min:                    3
                max:                    40
        birthDate:
            - DateTime:
                groups:
                    -                   troopMember
        pesel:
            - Wyd2016Bundle\Validator\Constraints\ContainsPesel:
                groups:
                    -                   troopMember
        fatherName:
            - Length:
                groups:
                    -                   troopMember
                min:                    2
                max:                    50
        otherPermissions:
            - Length:
                max:                    255
        profession:
            - Length:
                max:                    255
        comments:
            - Length:
                max:                    255
