Wyd2016Bundle\Entity\Volunteer:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:                     pesel
            ignoreNull:                 true
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstName:
            - Length:
                groups:
                    -                   troopMember
                max:                    50
                min:                    2
            - NotBlank:
                groups:
                    -                   troopMember
        lastName:
            - Length:
                groups:
                    -                   troopMember
                max:                    50
                min:                    2
            - NotBlank:
                groups:
                    -                   troopMember
        address:
            - Length:
                groups:
                    -                   troopMember
                max:                    255
                min:                    10
            - NotBlank:
                groups:
                    -                   troopMember
        phone:
            - Length:
                groups:
                    -                   troopMember
                max:                    15
                min:                    8
            - NotBlank:
                groups:
                    -                   troopMember
            - Regex:
                groups:
                    -                   troopMember
                pattern:                "/^[0-9 \+\-\(\)]{8,15}$/"
        email:
            - Email:
                groups:
                    -                   troopMember
            - Length:
                groups:
                    -                   troopMember
                max:                    40
                min:                    3
            - NotBlank:
                groups:
                    -                   troopMember
        birthDate:
            - DateTime:
                groups:
                    -                   troopMember
        pesel:
            - Wyd2016Bundle\Validator\Constraints\ContainsPesel:
                groups:
                    -                   troopMember
        fatherName:
            - Length:
                groups:
                    -                   supplement
                    -                   troopMember
                max:                    50
                min:                    2
            - NotBlank:
                groups:
                    -                   supplement
                    -                   troopMember
        otherPermissions:
            - Length:
                max:                    255
        profession:
            - Length:
                max:                    255
        comments:
            - Length:
                max:                    255
