Wyd2016Bundle\Entity\Group:
    options:
        collate:                        utf8_general_ci
    repositoryClass:                    Wyd2016Bundle\Entity\Repository\GroupRepository
    table:                              "`group`"
    type:                               entity

    id:
        id:
            generator:
                strategy:               AUTO
            type:                       integer
    fields:
        status:
            type:                       smallint
        activationHash:
            length:                     32
            name:                       activation_hash
            options:
                fixed:                  true
            type:                       string
            unique:                     true
        name:
            length:                     50
            type:                       string
        datesId:
            name:                       dates_id
            type:                       smallint
        comments:
            length:                     255
            nullable:                   true
            type:                       string
        createdAt:
            name:                       created_at
            type:                       datetime
        updatedAt:
            name:                       updated_at
            type:                       datetime

    oneToOne:
        leader:
            targetEntity:               Wyd2016Bundle\Entity\Pilgrim

    oneToMany:
        members:
            cascade:
                -                       persist
            mappedBy:                   group
            targetEntity:               Wyd2016Bundle\Entity\Pilgrim

    indexes:
        g_index_1:
            columns:                    status

    lifecycleCallbacks:
        postLoad:
            -                           initializeCollections
