Wyd2016Bundle\Entity\PilgrimApplication:
    options:
        collate:                        utf8_general_ci
    table:                              pilgrim_application
    type:                               entity

    id:
        id:
            generator:
                strategy:               AUTO
            type:                       integer
    fields:
        status:
            type:                       smallint
        activationHash:
            length:                     32
            name:                       activation_hash
            type:                       string
            unique:                     true
        firstName:
            length:                     50
            name:                       first_name
            type:                       string
        lastName:
            length:                     50
            name:                       last_name
            type:                       string
        countryId:
            name:                       country_id
            type:                       smallint
        address:
            length:                     255
            type:                       string
        phone:
            length:                     15
            type:                       string
        mail:
            length:                     40
            type:                       string
            unique:                     true
        accomodationId:
            name:                       accomodation_id
            type:                       smallint
        dateFrom:
            name:                       date_from
            type:                       date
        dateTo:
            name:                       date_to
            type:                       date

    indexes:
        sa_index_1:
            columns:                    status
