Wyd2016Bundle\Entity\Troop:
    options:
        collate:                        utf8_general_ci
    repositoryClass:                    Wyd2016Bundle\Entity\Repository\TroopRepository
    table:                              troop
    type:                               entity

    id:
        id:
            generator:
                strategy:               AUTO
            type:                       integer
    fields:
        status:
            type:                       smallint
        activationHash:
            length:                     32
            name:                       activation_hash
            options:
                fixed:                  true
            type:                       string
            unique:                     true
        name:
            length:                     50
            type:                       string
        ownTent:
            name:                       own_tent
            type:                       boolean
        datesId:
            name:                       dates_id
            type:                       smallint
        comments:
            length:                     255
            nullable:                   true
            type:                       string
        createdAt:
            name:                       created_at
            type:                       date

    oneToOne:
        leader:
            targetEntity:               Wyd2016Bundle\Entity\Volunteer

    oneToMany:
        members:
            cascade:
                -                       persist
            mappedBy:                   troop
            targetEntity:               Wyd2016Bundle\Entity\Volunteer

    indexes:
        t_index_1:
            columns:                    status

    lifecycleCallbacks:
        postLoad:
            -                           initializeCollections
