Wyd2016Bundle\Entity\User:
    options:
        collate:                        utf8_general_ci
    repositoryClass:                    Wyd2016Bundle\Entity\Repository\UserRepository
    table:                              user
    type:                               entity

    id:
        id:
            generator:
                strategy:               AUTO
            type:                       integer
    fields:
        apiToken:
            length:                     32
            name:                       api_token
            nullable:                   true
            options:
                fixed:                  true
            type:                       string

    oneToMany:
        actions:
            cascade:
                -                       persist
            mappedBy:                   user
            targetEntity:               Wyd2016Bundle\Entity\Action
