Wyd2016Bundle\Entity\Volunteer:
    options:
        collate:                        utf8_general_ci
    repositoryClass:                    Wyd2016Bundle\Entity\Repository\VolunteerRepository
    table:                              volunteer
    type:                               entity

    id:
        id:
            generator:
                strategy:               AUTO
            type:                       integer
    fields:
        status:
            type:                       smallint
        activationHash:
            length:                     32
            name:                       activation_hash
            options:
                fixed:                  true
            type:                       string
            unique:                     true
        firstName:
            length:                     50
            name:                       first_name
            type:                       string
        lastName:
            length:                     50
            name:                       last_name
            type:                       string
        address:
            length:                     255
            type:                       string
        phone:
            length:                     15
            type:                       string
        email:
            length:                     40
            type:                       string
            unique:                     true
        country:
            length:                     2
            options:
                fixed:                  true
            type:                       string
        birthDate:
            name:                       birth_date
            type:                       date
        gradeId:
            name:                       grade_id
            nullable:                   true
            type:                       smallint
        regionId:
            name:                       region_id
            nullable:                   true
            type:                       smallint
        districtId:
            name:                       district_id
            nullable:                   true
            options:
                unsigned:               true
            type:                       smallint
        pesel:
            nullable:                   true
            type:                       bigint
        serviceMainId:
            name:                       service_main_id
            type:                       smallint
        serviceExtraId:
            name:                       service_extra_id
            nullable:                   true
            type:                       smallint
        permissions:
            length:                     255
            nullable:                   true
            type:                       string
        profession:
            length:                     255
            nullable:                   true
            type:                       string
        datesId:
            name:                       dates_id
            type:                       smallint
        comments:
            length:                     255
            nullable:                   true
            type:                       string
        createdAt:
            name:                       created_at
            type:                       datetime
        updatedAt:
            name:                       updated_at
            type:                       datetime

    manyToOne:
        troop:
            cascade:
                -                       persist
            inversedBy:                 members
            targetEntity:               Wyd2016Bundle\Entity\Troop

    oneToMany:
        languages:
            cascade:
                -                       persist
            mappedBy:                   volunteer
            targetEntity:               Wyd2016Bundle\Entity\Language

    indexes:
        v_index_1:
            columns:                    status

    lifecycleCallbacks:
        postLoad:
            -                           initializeCollections
