registration_group_form:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:groupForm
    methods:                            [GET|POST]
    path:                               /group
