registration_pilgrim_form:
    defaults:
        _controller:                    Wyd2016Bundle:Registration:pilgrimForm
    methods:                            [GET|POST]
    path:                               /pilgrim
