admin_search_index:
    defaults:
        _controller:                    Wyd2016Bundle:Admin/Search:index
    methods:                            [GET|POST]
    path:                               /admin/search
